services:
  server: 
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/:/app
  mongodb:
    image: mongo
  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm run start
    volumes:
      - ./client:/app
      - /app/node_modules


